# Generated by Django 2.2.6 on 2019-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
